package chipyard.example

// Auto-generated by scripts/sync_cgra_blackbox.py from $top_module.
// Do not edit by hand; regenerate after PyMTL3 RTL changes.
$rocc_funct_object

$cgra_cmd_object

object CGRAGenerated {
  val params = CGRAParams(
    intraPktWidth = $intra_width,
    interPktWidth = $inter_width,
    dataPayloadWidth = $data_payload_width,
    dataWidth = $data_width,
    payloadWidth = $payload_width,
    idWidth = $id_width,
    addrWidth = $addr_width,
    xTiles = $x_tiles,
    yTiles = $y_tiles,
    cmdWidth = $cmd_width,
    numTiles = $num_tiles,
    addressLower = $address_lower,
    addressUpper = $address_upper,
    hasBoundaryPorts = $has_boundary_ports,
    packetLayout = CGRAPacketLayout(
      cmdLsb = $pkt_cmd_lsb,
      dataPayloadLsb = $pkt_data_payload_lsb,
      dataPredicateLsb = $pkt_data_predicate_lsb,
      dataAddrLsb = $pkt_data_addr_lsb,
      opaqueLsb = $pkt_opaque_lsb,
      dstTileLsb = $pkt_dst_tile_lsb
    ),
    dma = CGRADMAParams(
      enabled = $dma_enabled,
      dramAddrWidth = $dma_dram_addr_width,
      dramDataWidth = $dma_dram_data_width,
      dramMaskWidth = $dma_dram_mask_width,
      spmAddrWidth = $dma_spm_addr_width,
      nbytesWidth = $dma_nbytes_width,
      tagWidth = $dma_tag_width,
      spmWords = $dma_spm_words,
      writeReqAddrLsb = $dma_write_req_addr_lsb,
      writeReqDataLsb = $dma_write_req_data_lsb,
      writeReqMaskLsb = $dma_write_req_mask_lsb,
      descriptorSpmLsb = $dma_descriptor_spm_lsb,
      descriptorNbytesLsb = $dma_descriptor_nbytes_lsb,
      descriptorTagLsb = $dma_descriptor_tag_lsb,
      descriptorWidth = $dma_descriptor_width,
      cmdConfigDramAddrLo = $dma_cmd_config_dram_addr_lo,
      cmdConfigDramAddrHi = $dma_cmd_config_dram_addr_hi,
      cmdConfigSpmAddr = $dma_cmd_config_spm_addr,
      cmdConfigBytes = $dma_cmd_config_bytes,
      cmdConfigTag = $dma_cmd_config_tag,
      cmdMvin = $dma_cmd_mvin,
      cmdMvout = $dma_cmd_mvout,
      cmdDone = $dma_cmd_done,
      packetTemplates = Seq($dma_packet_templates)
    ),
    topModuleName = "$top_module",
    wrapperModuleName = "$wrapper_module",
    rtlResource = "$rtl_resource",
    wrapperResource = "$wrapper_resource"
  )
}
