//-------------------------------------------------------------------------
// $wrapper_module.v
//-------------------------------------------------------------------------
// Auto-generated by scripts/sync_cgra_blackbox.py.
// Wraps PyMTL3-generated $top_module and flattens struct/array ports
// for Chisel BlackBox compatibility.
//-------------------------------------------------------------------------

module $wrapper_module (
$port_list
);

  $intra_type w_recv_from_cpu_pkt_msg;
  $intra_type w_send_to_cpu_pkt_msg;
  $inter_type w_recv_from_inter_cgra_noc_msg;
  $inter_type w_send_to_inter_cgra_noc_msg;
$boundary_wires

  assign w_recv_from_cpu_pkt_msg = recv_from_cpu_pkt_msg;
  assign send_to_cpu_pkt_msg = w_send_to_cpu_pkt_msg;
  assign w_recv_from_inter_cgra_noc_msg = recv_from_inter_cgra_noc_msg;
  assign send_to_inter_cgra_noc_msg = w_send_to_inter_cgra_noc_msg;

$boundary_assigns

  $top_module cgra_inst (
$inst_port_list
  );

endmodule
