package chipyard.example

// Auto-generated by scripts/sync_cgra_blackbox.py from $top_module.
// Do not edit by hand; regenerate after PyMTL3 RTL changes.
object CGRAGenerated {
  val params = CGRAParams(
    intraPktWidth = $intra_width,
    interPktWidth = $inter_width,
    dataPayloadWidth = $data_payload_width,
    dataWidth = $data_width,
    payloadWidth = $payload_width,
    idWidth = $id_width,
    addrWidth = $addr_width,
    xTiles = $x_tiles,
    yTiles = $y_tiles,
    cmdWidth = $cmd_width,
    numTiles = $num_tiles,
    addressLower = $address_lower,
    addressUpper = $address_upper,
    hasBoundaryPorts = $has_boundary_ports,
    topModuleName = "$top_module",
    wrapperModuleName = "$wrapper_module",
    rtlResource = "$rtl_resource",
    wrapperResource = "$wrapper_resource"
  )
}
