multi_cgra_defaults:
  rows: 2
  columns: 2

cgra_defaults:
  rows: 4
  columns: 4
  configMemSize: 16

tile_defaults:
  num_registers: 16
  fu_types: ["add", "mul", "logic", "cmp", "grant", "phi", "mem", "return"]
