/* Generated by scripts/generate_accels.py. Do not edit. */
#ifndef ACCEL_GENERATED_H
#define ACCEL_GENERATED_H

#include "accel.h"

#define ACCEL_ROUTED 0
#define ACCEL_COUNT 3u

static const accel_t GEMMINI = {.id = 0u, .control = UINT64_C(0x60012000), .spm = UINT64_C(0x60000000), .spm_bytes = 65536u};
static const accel_t CGRA = {.id = 1u, .control = UINT64_C(0x60011000), .spm = UINT64_C(0x60010000), .spm_bytes = 512u};
static const accel_t POOL = {.id = 2u, .control = UINT64_C(0x0), .spm = UINT64_C(0x0), .spm_bytes = 0u};

#endif
