/* Generated by scripts/generate_aes_auto_job.py. Do not edit. */
#ifndef AES_AUTO_JOB_H
#define AES_AUTO_JOB_H

#include <stdint.h>

#define AES_AUTO_CIPHERTEXT_ADDRESS UINT64_C(0x81000000)
#define AES_AUTO_CIPHERTEXT_SIZE_BYTES 128u
#define AES_AUTO_COMPLETION_ADDRESS UINT64_C(0x81000080)

#endif
