/* Generated by scripts/generate_auto_links.py. Do not edit. */
#ifndef AUTO_LINK_GENERATED_H
#define AUTO_LINK_GENERATED_H

#define AUTO_LINK_STAGE_CONV1 0u
#define AUTO_LINK_STAGE_RELU1 1u
#define AUTO_LINK_STAGE_CONV2 2u
#define AUTO_LINK_STAGE_ADD_RELU 3u

#endif
