#ifndef CGRA_PROTOCOL_H
#define CGRA_PROTOCOL_H

#include "generated/cgra_protocol_generated.h"
#include "rocc.h"

#define CGRA_STATUS(result) ROCC_INSTRUCTION_D(0, result, CGRA_FUNCT_STATUS)
#define CGRA_WAIT(result) ROCC_INSTRUCTION_D(0, result, CGRA_FUNCT_WAIT)
#define CGRA_RAW_PKT_LO(lo) ROCC_INSTRUCTION_S(0, lo, CGRA_FUNCT_RAW_PKT_LO)
#define CGRA_RAW_PKT_MID(mid) ROCC_INSTRUCTION_S(0, mid, CGRA_FUNCT_RAW_PKT_MID)
#define CGRA_RAW_PKT_HI(hi) ROCC_INSTRUCTION_S(0, hi, CGRA_FUNCT_RAW_PKT_HI)
#define CGRA_SET_EXPECTED_COMPLETES(count)                                     \
  ROCC_INSTRUCTION_S(0, count, CGRA_FUNCT_SET_EXPECTED_COMPLETES)
#define CGRA_RESULT(result) ROCC_INSTRUCTION_D(0, result, CGRA_FUNCT_RESULT)
#define CGRA_RAW_PKT_TOP(top) ROCC_INSTRUCTION_S(0, top, CGRA_FUNCT_RAW_PKT_TOP)
#define CGRA_LOAD_RESULT(result)                                               \
  ROCC_INSTRUCTION_D(0, result, CGRA_FUNCT_LOAD_RESULT)
#define CGRA_SPM_PKT_HI(hi) ROCC_INSTRUCTION_S(0, hi, CGRA_FUNCT_SPM_PKT_HI)
#define CGRA_SPM_PKT_TOP(top) ROCC_INSTRUCTION_S(0, top, CGRA_FUNCT_SPM_PKT_TOP)

enum {
  OPT_START = 0,
  OPT_NAH = 1,
  OPT_ADD = 2,
  OPT_INC = 3,
  OPT_SUB = 4,
  OPT_LLS = 5,
  OPT_LRS = 6,
  OPT_MUL = 7,
  OPT_OR = 8,
  OPT_XOR = 9,
  OPT_AND = 10,
  OPT_NOT = 11,
  OPT_LD = 12,
  OPT_STR = 13,
  OPT_EQ = 14,
  OPT_REM_INCLUSIVE_END = 15,
  OPT_GRT_PRED = 16,
  OPT_PHI = 17,
  OPT_MUL_ADD = 18,
  OPT_MUL_SUB = 19,
  OPT_MUL_LLS = 20,
  OPT_MUL_LRS = 21,
  OPT_MUL_ADD_LLS = 22,
  OPT_MUL_SUB_LLS = 23,
  OPT_MUL_SUB_LRS = 24,
  OPT_ADD_CONST = 25,
  OPT_DIV = 26,
  OPT_SEL = 27,
  OPT_LD_CONST = 28,
  OPT_MUL_CONST = 29,
  OPT_MUL_CONST_ADD = 30,
  OPT_PAS = 31,
  OPT_PHI_CONST = 32,
  OPT_EQ_CONST = 33,
  OPT_GRT_ALWAYS = 34,
  OPT_RET = 35,
  OPT_SUB_CONST = 36,
  OPT_FADD = 37,
  OPT_FSUB = 38,
  OPT_FADD_CONST = 39,
  OPT_FINC = 40,
  OPT_FMUL = 41,
  OPT_FMUL_CONST = 42,
  OPT_BIT_NOT = 43,
  OPT_REM = 44,
  OPT_NE = 45,
  OPT_NE_CONST = 46,
  OPT_GRT_ONCE = 47,
  OPT_DIV_INCLUSIVE_START = 48,
  OPT_DIV_INCLUSIVE_END = 49,
  OPT_VEC_INC = 50,
  OPT_VEC_ADD = 51,
  OPT_VEC_ADD_CONST = 52,
  OPT_VEC_SUB = 53,
  OPT_VEC_SUB_CONST = 54,
  OPT_VEC_MUL = 55,
  OPT_VEC_REDUCE_ADD = 56,
  OPT_VEC_REDUCE_MUL = 57,
  OPT_STR_CONST = 58,
  OPT_REM_INCLUSIVE_START = 59,
  OPT_LT = 60,
  OPT_GTE = 61,
  OPT_GT = 62,
  OPT_LTE = 63,
  OPT_RET_VOID = 64,
  OPT_DIV_CONST = 65,
  OPT_VEC_REDUCE_ADD_BASE = 68,
  OPT_VEC_REDUCE_MUL_BASE = 69,
  OPT_VEC_INC_COMBINED = 70,
  OPT_VEC_ADD_COMBINED = 71,
  OPT_VEC_ADD_CONST_COMBINED = 72,
  OPT_VEC_SUB_COMBINED = 73,
  OPT_VEC_SUB_CONST_COMBINED = 74,
  OPT_VEC_MUL_COMBINED = 75,
  OPT_VEC_REDUCE_ADD_GLOBAL = 76,
  OPT_VEC_REDUCE_MUL_GLOBAL = 77,
  OPT_VEC_REDUCE_ADD_BASE_GLOBAL = 78,
  OPT_VEC_REDUCE_MUL_BASE_GLOBAL = 79,
  OPT_CONST = 80,
  OPT_ADD_CONST_LD = 81,
  OPT_INC_NE_CONST_NOT_GRT = 82,
  OPT_LOOP_CONTROL = 83,
  OPT_PHI_START = 84,
  OPT_LOOP_COUNT = 85,
  OPT_LOOP_DELIVERY = 86,
  OPT_EXTRACT_PREDICATE = 87,
  OPT_GRT_ONCE_CONST = 88,
  OPT_STREAM_LD = 89,
  OPT_GTE_CONST = 90,
  OPT_GEP = 92,
  OPT_GEP_CONST = 93,
  OPT_GEP_2D = 94,
  OPT_GEP_2D_CONST = 95,
  OPT_LLS_CONST = 96,
  OPT_GT_CONST = 97,
  OPT_LT_CONST = 98,
};

enum {
  PORT_NAH = 0,
  PORT_NORTH = 1,
  PORT_SOUTH = 2,
  PORT_WEST = 3,
  PORT_EAST = 4,
  PORT_NORTHWEST = 5,
  PORT_NORTHEAST = 6,
  PORT_SOUTHEAST = 7,
  PORT_SOUTHWEST = 8,
};

#endif
