/* Generated by scripts/generate_cgra_spm_window.py. Do not edit. */
#ifndef CGRA_SPM_WINDOW_H
#define CGRA_SPM_WINDOW_H

#include <stdint.h>

#define CGRA_SPM_WINDOW_BASE UINT64_C(0x60010000)
#define CGRA_SPM_WINDOW_SIZE_BYTES 128u
#define CGRA_SPM_OUTBOUND_WORD 0u
#define CGRA_SPM_INBOUND_WORD 0u
#define CGRA_SPM_INBOUND_WORDS 0u

#endif
