/* Generated by scripts/generate_gemmini_ext_spm.py. Do not edit. */
#ifndef GEMMINI_EXT_SPM_H
#define GEMMINI_EXT_SPM_H

#include <stdint.h>

#define GEMMINI_EXT_SPM_BASE UINT64_C(0x60000000)
#define GEMMINI_EXT_SPM_SIZE_BYTES 65536u

#endif
