/* Generated by scripts/generate_shared_spm.py. Do not edit. */
#ifndef SHARED_SPM_H
#define SHARED_SPM_H

#include <stdint.h>

#define SHARED_SPM_BASE UINT64_C(0x60000000)
#define SHARED_SPM_SIZE_BYTES 65536u
#define SHARED_SPM_SLOT_COUNT 2u
#define SHARED_SPM_SLOT_SIZE_BYTES 1024u
#define SHARED_SPM_SLOT0_BASE UINT64_C(0x6000f800)
#define SHARED_SPM_SLOT1_BASE UINT64_C(0x6000fc00)

#endif
