#!/usr/bin/env python3
"""Generate Chipyard-side Scala metadata for OpenFPGA demos."""

from __future__ import annotations

import hashlib
import re

from bitstream import PackedBitstream
from config import ROOT, DemoConfig, FieldSpec, UserInterfaceSpec


CHIPYARD_CONFIG_GENERATED = (
    ROOT
    / "chipyard"
    / "generators"
    / "chipyard"
    / "src"
    / "main"
    / "scala"
    / "config"
    / "OpenFPGAConfigGenerated.scala"
)


def _scala_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _field_seq(fields: list[FieldSpec]) -> str:
    if not fields:
        return "Seq.empty"
    rendered = ", ".join(
        f"OpenFPGAUserField({_scala_string(field.name)}, {field.width}, {field.lsb})"
        for field in fields
    )
    return f"Seq({rendered})"


def _compatible(peripheral_name: str) -> str:
    return "ucbbar," + peripheral_name.replace("_", "-").lower()


def _dts_node_name(peripheral_name: str, base_address: int) -> str:
    text = re.sub(r"[^A-Za-z0-9,._+-]+", "-", peripheral_name.replace("_", "-").lower()).strip("-")
    if not text or not text[0].isalpha():
        text = f"openfpga-{text}"

    max_name_len = 47 - 1 - len(f"{base_address:x}")
    if max_name_len < 10:
        raise ValueError(f"soc.base_address 0x{base_address:x} leaves too little room for a DTS node name")
    if len(text) > max_name_len:
        suffix = hashlib.sha1(text.encode("utf-8")).hexdigest()[:8]
        text = f"{text[: max_name_len - len(suffix) - 1].rstrip('-')}-{suffix}"
    return text


def write_scala_generated(demo: DemoConfig, user_interface: UserInterfaceSpec, bitstream: PackedBitstream) -> None:
    cfg = demo.architecture.config_protocol
    input_register = user_interface.input_register
    output_register = user_interface.output_register
    text = f"""package chipyard.example

// Auto-generated by scripts/openfpga/chipyard.py.
case class OpenFPGAUserField(name: String, width: Int, lsb: Int)

object {demo.chipyard.scala_object} {{
  val Name = {_scala_string(demo.name)}
  val ApplicationName = {_scala_string(demo.application.name)}
  val ConfigName = {_scala_string(demo.chipyard.config_name)}
  val PeripheralName = {_scala_string(demo.chipyard.peripheral_name)}
  val DtsNodeName = {_scala_string(_dts_node_name(demo.chipyard.peripheral_name, demo.soc.base_address))}
  val Compatible = {_scala_string(_compatible(demo.chipyard.peripheral_name))}
  val WrapperModule = {_scala_string(demo.chipyard.wrapper_module)}
  val WrapperPath = {_scala_string(str(demo.wrapper_path.resolve()))}

  val BaseAddress = BigInt("{demo.soc.base_address:x}", 16)
  val Size = BigInt("{demo.soc.size:x}", 16)

  val BitstreamLength = {bitstream.parsed_length}
  val CfgWordWidth = {cfg.word_width}
  val CfgAddrWidth = {cfg.address_width}
  val CfgDataWidth = {cfg.data_width}

  val InputRegisterName = {_scala_string(input_register.name)}
  val InputWidth = {input_register.width}
  val InputFields = {_field_seq(input_register.fields)}

  val OutputRegisterName = {_scala_string(output_register.name)}
  val OutputWidth = {output_register.width}
  val OutputFields = {_field_seq(output_register.fields)}
}}
"""
    demo.scala_generated_path.parent.mkdir(parents=True, exist_ok=True)
    demo.scala_generated_path.write_text(text, encoding="utf-8")


def write_chipyard_config(demo: DemoConfig) -> None:
    text = f"""package chipyard

import org.chipsalliance.cde.config.Config

// Auto-generated by scripts/openfpga/chipyard.py.
class {demo.chipyard.config_name} extends Config(
  new chipyard.example.WithOpenFPGADemo() ++
  new freechips.rocketchip.rocket.WithNHugeCores(1) ++
  new chipyard.config.AbstractConfig)
"""
    CHIPYARD_CONFIG_GENERATED.parent.mkdir(parents=True, exist_ok=True)
    CHIPYARD_CONFIG_GENERATED.write_text(text, encoding="utf-8")
