multi_cgra_defaults:
  rows: 1
  columns: 1

cgra_defaults:
  rows: 4
  columns: 4
  configMemSize: 6

tile_defaults:
  num_registers: 8
  fu_types: ["add", "mul", "logic", "cmp", "grant", "phi", "mem", "return"]
