#!/usr/bin/env python3
"""Generate the projected residual demo's dimensions and reference output."""

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def conv(
    source,
    weights,
    rows,
    columns,
    channels,
    outputs,
    kernel,
    stride,
    padding,
    relu=False,
):
    height = (rows + 2 * padding - kernel) // stride + 1
    width = (columns + 2 * padding - kernel) // stride + 1
    result = []
    for row in range(height):
        for column in range(width):
            for out in range(outputs):
                total = 0
                for y in range(kernel):
                    in_row = row * stride + y - padding
                    if in_row < 0 or in_row >= rows:
                        continue
                    for x in range(kernel):
                        in_column = column * stride + x - padding
                        if in_column < 0 or in_column >= columns:
                            continue
                        source_index = (in_row * columns + in_column) * channels
                        weight_index = ((y * kernel + x) * channels) * outputs + out
                        for channel in range(channels):
                            total += (
                                source[source_index + channel]
                                * weights[weight_index + channel * outputs]
                            )
                result.append(min(127, max(0 if relu else -128, total)))
    return result


def reference(args):
    source = [
        (row * 7 + column * 3 + channel * 2) % 7 - 3
        for row in range(args.height)
        for column in range(args.width)
        for channel in range(args.inputs)
    ]
    weights1 = [
        (y * 3 + x * 2 + channel + out * 2) % 5 - 2
        for y in range(args.kernel)
        for x in range(args.kernel)
        for channel in range(args.inputs)
        for out in range(args.channels)
    ]
    weights2 = [
        (y + x * 3 + channel * 2 + out) % 3 - 1
        for y in range(args.kernel)
        for x in range(args.kernel)
        for channel in range(args.channels)
        for out in range(args.channels)
    ]
    projection = [
        (channel * 3 + out) % 5 - 2
        for channel in range(args.inputs)
        for out in range(args.channels)
    ]
    height = (args.height + 2 * args.padding - args.kernel) // args.stride + 1
    width = (args.width + 2 * args.padding - args.kernel) // args.stride + 1
    intermediate = conv(
        source,
        weights1,
        args.height,
        args.width,
        args.inputs,
        args.channels,
        args.kernel,
        args.stride,
        args.padding,
        True,
    )
    main = conv(
        intermediate,
        weights2,
        height,
        width,
        args.channels,
        args.channels,
        args.kernel,
        1,
        args.padding,
    )
    skip = conv(
        source,
        projection,
        args.height,
        args.width,
        args.inputs,
        args.channels,
        1,
        args.stride,
        0,
    )
    return [max(value + skip[index], 0) for index, value in enumerate(main)]


def header(args, expected):
    height = (args.height + 2 * args.padding - args.kernel) // args.stride + 1
    width = (args.width + 2 * args.padding - args.kernel) // args.stride + 1
    lines = [
        "/* Generated by scripts/block_data.py. Do not edit. */",
        "#ifndef BLOCK_DATA_H",
        "#define BLOCK_DATA_H",
        "",
        "#include <stdint.h>",
        "",
        "enum {",
        f"  INPUT_H = {args.height},",
        f"  INPUT_W = {args.width},",
        f"  INPUT_CHANNELS = {args.inputs},",
        f"  CHANNELS = {args.channels},",
        f"  KERNEL = {args.kernel},",
        f"  STRIDE = {args.stride},",
        f"  PADDING = {args.padding},",
        f"  HEIGHT = {height},",
        f"  WIDTH = {width},",
        "};",
        "",
        "static const int32_t expected[HEIGHT][WIDTH][CHANNELS] = {",
    ]
    for row in range(height):
        lines.append("  {")
        for column in range(width):
            start = (row * width + column) * args.channels
            values = ", ".join(
                str(value) for value in expected[start : start + args.channels]
            )
            lines.append(f"    {{{values}}},")
        lines.append("  },")
    lines.extend(["};", "", "#endif", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--height", type=int, default=32)
    parser.add_argument("--width", type=int, default=32)
    parser.add_argument("--inputs", type=int, default=16)
    parser.add_argument("--channels", type=int, default=32)
    parser.add_argument("--kernel", type=int, default=3)
    parser.add_argument("--stride", type=int, default=2)
    parser.add_argument("--padding", type=int, default=1)
    parser.add_argument(
        "--output", type=Path, default=ROOT / "tests/generated/block_data.h"
    )
    args = parser.parse_args()
    expected = reference(args)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header(args, expected), encoding="utf-8")
    print(f"Generated {args.output}: {len(expected)} output values")


if __name__ == "__main__":
    main()
