#!/usr/bin/env python3
"""Generate dimensions and INT8 reference outputs for projected residual blocks."""

import argparse
from pathlib import Path

from block_data import conv

ROOT = Path(__file__).resolve().parents[1]
KERNEL = 3
STRIDE = 2
PADDING = 1


def reference(args):
    rows, columns = args.height, args.width
    source = [
        3 * ((row * 7 + column * 3 + channel * 2) % 7 - 3)
        for row in range(rows)
        for column in range(columns)
        for channel in range(args.channels[0])
    ]
    blocks = []
    expected = []
    parameters = []
    for index, (inputs, channels) in enumerate(zip(args.channels, args.channels[1:])):
        seed = index + 1
        height = (rows + 2 * PADDING - KERNEL) // STRIDE + 1
        width = (columns + 2 * PADDING - KERNEL) // STRIDE + 1
        blocks.append((rows, columns, inputs, height, width, channels, seed))
        weights1 = [
            (y * 3 + x * 2 + channel + out * 2 + seed) % 5 - 2
            for y in range(KERNEL)
            for x in range(KERNEL)
            for channel in range(inputs)
            for out in range(channels)
        ]
        weights2 = [
            (y + x * 3 + channel * 2 + out + seed) % 3 - 1
            for y in range(KERNEL)
            for x in range(KERNEL)
            for channel in range(channels)
            for out in range(channels)
        ]
        projection = [
            (channel * 3 + out + seed * 2) % 5 - 2
            for channel in range(inputs)
            for out in range(channels)
        ]
        parameters.append((weights1, weights2, projection))
        intermediate = conv(
            source,
            weights1,
            rows,
            columns,
            inputs,
            channels,
            KERNEL,
            STRIDE,
            PADDING,
            True,
        )
        main = conv(
            intermediate,
            weights2,
            height,
            width,
            channels,
            channels,
            KERNEL,
            1,
            PADDING,
        )
        skip = conv(source, projection, rows, columns, inputs, channels, 1, STRIDE, 0)
        source = [min(127, max(value + bypass, 0)) for value, bypass in zip(main, skip)]
        expected.append(source)
        rows, columns = height, width
    return blocks, expected, parameters


def header(args, blocks, expected, parameters):
    core = max(min(args.tile_rows, b[3]) * b[4] * b[5] for b in blocks)
    halo = max(min(args.tile_rows + 2 * PADDING, b[3]) * b[4] * b[5] for b in blocks)
    lines = [
        "/* Generated by scripts/blocks_data.py. Do not edit. */",
        "#ifndef BLOCKS_DATA_H",
        "#define BLOCKS_DATA_H",
        "",
        "#include <stdint.h>",
        "",
        "enum {",
        f"  BLOCKS = {len(blocks)},",
        f"  INPUT_H = {args.height},",
        f"  INPUT_W = {args.width},",
        f"  INPUT_CHANNELS = {args.channels[0]},",
        f"  TILE_ROWS = {args.tile_rows},",
        f"  KERNEL = {KERNEL},",
        f"  STRIDE = {STRIDE},",
        f"  PADDING = {PADDING},",
        f"  CORE_WORDS = {core},",
        f"  HALO_WORDS = {halo},",
        "};",
        "",
        "typedef struct {",
        "  unsigned input_rows, input_columns, input_channels;",
        "  unsigned rows, columns, channels, seed;",
        "} block_t;",
        "",
        "static const block_t blocks[BLOCKS] = {",
    ]
    for block in blocks:
        lines.append("  {" + ", ".join(str(value) for value in block) + "},")
    lines.extend(["};", ""])
    arrays = {
        "weights1": [values[0] for values in parameters],
        "weights2": [values[1] for values in parameters],
        "projection": [values[2] for values in parameters],
        "expected": expected,
    }
    for name, tensors in arrays.items():
        for index, values in enumerate(tensors):
            lines.append(
                f"static const int8_t {name}_{index}[{len(values)}] row_align(1) = {{"
            )
            for start in range(0, len(values), 32):
                lines.append(
                    "  " + ", ".join(str(v) for v in values[start : start + 32]) + ","
                )
            lines.extend(["};", ""])
        lines.append(f"static const int8_t *const {name}[BLOCKS] = {{")
        lines.extend(f"  {name}_{index}," for index in range(len(tensors)))
        lines.extend(["};", ""])
    lines.extend(["#endif", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--height", type=int, default=32)
    parser.add_argument("--width", type=int, default=32)
    parser.add_argument("--channels", type=int, nargs="+", default=[16, 32, 64])
    parser.add_argument("--tile-rows", type=int, default=2)
    parser.add_argument(
        "--output", type=Path, default=ROOT / "tests/generated/blocks_data.h"
    )
    args = parser.parse_args()
    blocks, expected, parameters = reference(args)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header(args, blocks, expected, parameters), encoding="utf-8")
    print(
        f"Generated {args.output}: {len(blocks)} blocks, "
        f"{sum(len(values) for values in expected)} output values"
    )


if __name__ == "__main__":
    main()
