#!/usr/bin/env python3
"""Generate the AES automatic-job address and key contract."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

import yaml

from generate_cgra_link_control import (
    PAGE_COUNT,
    PAGE_SIZE_BYTES,
    control_address,
    load_spm_ranges,
)
from generate_gemmini_ext_spm import require_int, require_mapping, write

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOC = ROOT / "configs" / "soc" / "autolink" / "gca.yaml"
DEFAULT_SCALA = (
    ROOT
    / "chipyard"
    / "generators"
    / "chipyard"
    / "src"
    / "main"
    / "scala"
    / "socgen"
    / "generated"
    / "AesAutoJobGenerated.scala"
)
DEFAULT_HEADER = ROOT / "tests" / "include" / "aes_auto_job.h"
OUTPUT_BYTES = 128
FLAG_BYTES = 4
ADDRESS_LIMIT = 1 << 64
KEY_LIMIT = 1 << 256


@dataclass(frozen=True)
class AesAutoJobContract:
    ciphertext_address: int
    completion_address: int
    key: int


def overlaps(first: tuple[int, int], second: tuple[int, int]) -> bool:
    first_base, first_size = first
    second_base, second_size = second
    return (
        first_base < second_base + second_size and second_base < first_base + first_size
    )


def load_contract(path: Path) -> AesAutoJobContract:
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(document, Mapping):
        raise ValueError(f"{path}: expected a mapping")
    accelerators = require_mapping(document, "accelerators", path)
    aes = require_mapping(accelerators, "aes", path)
    job = require_mapping(aes, "auto_job", path)
    mode = job.get("mode")
    if mode != "encrypt":
        raise ValueError(f"{path}: AES automatic mode must be 'encrypt'")

    contract = AesAutoJobContract(
        ciphertext_address=require_int(job, "ciphertext_address", path),
        completion_address=require_int(job, "completion_address", path),
        key=require_int(job, "key", path),
    )
    if contract.ciphertext_address % OUTPUT_BYTES != 0:
        raise ValueError(f"{path}: AES ciphertext address must be 128-byte aligned")
    if contract.completion_address % FLAG_BYTES != 0:
        raise ValueError(f"{path}: AES completion address must be 4-byte aligned")
    if not 0 < contract.key < KEY_LIMIT:
        raise ValueError(f"{path}: AES key must be a nonzero 256-bit value")
    output = (contract.ciphertext_address, OUTPUT_BYTES)
    flag = (contract.completion_address, FLAG_BYTES)
    if output[0] < 0 or output[0] + output[1] > ADDRESS_LIMIT:
        raise ValueError(f"{path}: AES ciphertext range exceeds 64-bit addresses")
    if flag[0] < 0 or flag[0] + flag[1] > ADDRESS_LIMIT:
        raise ValueError(f"{path}: AES completion range exceeds 64-bit addresses")
    if overlaps(output, flag):
        raise ValueError(f"{path}: AES ciphertext and completion ranges overlap")

    reserved = load_spm_ranges(path)
    reserved.append((control_address(path), PAGE_COUNT * PAGE_SIZE_BYTES))
    if any(overlaps(output, region) or overlaps(flag, region) for region in reserved):
        raise ValueError(
            f"{path}: AES automatic-job range collides with an accelerator window"
        )
    return contract


def scala_text(contract: AesAutoJobContract) -> str:
    return f"""package chipyard.socgen.generated

// Generated by scripts/generate_aes_auto_job.py. Do not edit.
object AesAutoJobGenerated {{
  val ciphertextAddress: BigInt = BigInt("{contract.ciphertext_address:x}", 16)
  val ciphertextBytes: Int = {OUTPUT_BYTES}
  val completionAddress: BigInt = BigInt("{contract.completion_address:x}", 16)
  val key: BigInt = BigInt("{contract.key:064x}", 16)
  val encrypt: Boolean = true
}}
"""


def header_text(contract: AesAutoJobContract) -> str:
    return f"""/* Generated by scripts/generate_aes_auto_job.py. Do not edit. */
#ifndef AES_AUTO_JOB_H
#define AES_AUTO_JOB_H

#include <stdint.h>

#define AES_AUTO_CIPHERTEXT_ADDRESS UINT64_C(0x{contract.ciphertext_address:x})
#define AES_AUTO_CIPHERTEXT_SIZE_BYTES {OUTPUT_BYTES}u
#define AES_AUTO_COMPLETION_ADDRESS UINT64_C(0x{contract.completion_address:x})

#endif
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--soc-yaml", type=Path, default=DEFAULT_SOC)
    parser.add_argument("--scala-out", type=Path, default=DEFAULT_SCALA)
    parser.add_argument("--header-out", type=Path, default=DEFAULT_HEADER)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    contract = load_contract(args.soc_yaml.resolve())
    write(args.scala_out, scala_text(contract), args.check)
    write(args.header_out, header_text(contract), args.check)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
