#!/usr/bin/env python3
"""Generate the CGRA SPM window address contract."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

import yaml

from generate_auto_links import DEFAULT_CACHE_BLOCK_SCALA, CgraBridge, load_config
from generate_gemmini_ext_spm import (
    is_power_of_two,
    require_int,
    require_mapping,
    write,
)

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOC = ROOT / "configs" / "soc" / "autolink" / "gca.yaml"
DEFAULT_CGRA_SCALA = (
    ROOT
    / "chipyard"
    / "generators"
    / "chipyard"
    / "src"
    / "main"
    / "scala"
    / "example"
    / "CGRAGenerated.scala"
)
DEFAULT_SCALA = (
    ROOT
    / "chipyard"
    / "generators"
    / "chipyard"
    / "src"
    / "main"
    / "scala"
    / "socgen"
    / "generated"
    / "CGRASpmWindowGenerated.scala"
)
DEFAULT_HEADER = ROOT / "tests" / "include" / "cgra_spm_window.h"


@dataclass(frozen=True)
class CgraSpmMetadata:
    data_width: int
    words: int

    @property
    def size_bytes(self) -> int:
        if self.data_width % 8 != 0:
            raise ValueError("generated CGRA SPM data width must contain whole bytes")
        return self.words * self.data_width // 8


@dataclass(frozen=True)
class CgraSpmWindowContract:
    base_address: int
    size_bytes: int


def load_metadata(path: Path) -> CgraSpmMetadata:
    text = path.read_text(encoding="utf-8")
    block = re.search(
        r"spmRead\s*=\s*CGRASpmReadParams\((?P<body>.*?)\n\s*\)", text, re.S
    )
    if block is None:
        raise ValueError(f"{path}: missing generated CGRA SPM metadata")
    body = block.group("body")
    enabled = re.search(r"enabled\s*=\s*(true|false)", body)
    data_width = re.search(r"dataWidth\s*=\s*(\d+)", body)
    words = re.search(r"words\s*=\s*(\d+)", body)
    if (
        enabled is None
        or enabled.group(1) != "true"
        or data_width is None
        or words is None
    ):
        raise ValueError(f"{path}: incomplete generated CGRA SPM metadata")
    return CgraSpmMetadata(int(data_width.group(1)), int(words.group(1)))


def load_contract(path: Path, metadata: CgraSpmMetadata) -> CgraSpmWindowContract:
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(document, Mapping):
        raise ValueError(f"{path}: expected a mapping")
    memory = require_mapping(document, "memory", path)
    window = require_mapping(memory, "cgra_spm_window", path)
    contract = CgraSpmWindowContract(
        base_address=require_int(window, "base_address", path),
        size_bytes=require_int(window, "size_bytes", path),
    )
    if not is_power_of_two(contract.size_bytes):
        raise ValueError(f"{path}: CGRA SPM window size must be a power of two")
    if contract.base_address % contract.size_bytes != 0:
        raise ValueError(f"{path}: CGRA SPM window base must be size aligned")
    if contract.size_bytes != metadata.size_bytes:
        raise ValueError(
            f"{path}: CGRA SPM window size {contract.size_bytes} does not match generated size {metadata.size_bytes}"
        )
    gemmini = require_mapping(memory, "gemmini_external_spm", path)
    gemmini_base = require_int(gemmini, "base_address", path)
    gemmini_size = require_int(gemmini, "size_bytes", path)
    if (
        contract.base_address < gemmini_base + gemmini_size
        and gemmini_base < contract.base_address + contract.size_bytes
    ):
        raise ValueError(f"{path}: CGRA and Gemmini SPM ranges overlap")
    return contract


def scala_text(contract: CgraSpmWindowContract, bridge: CgraBridge | None) -> str:
    if bridge is not None:
        return f"""package chipyard.socgen.generated

import chipyard.example.CGRASpmWindowParams
import chipyard.socgen.cgra.{{CgraRequantParams, CgraTensorBridgeParams}}

// Generated by scripts/generate_cgra_spm_window.py. Do not edit.
object CGRASpmWindowGenerated {{
  val baseAddress: BigInt = BigInt("{contract.base_address:x}", 16)
  val sizeBytes: Int = {bridge.window_bytes}
  val bridge = CgraTensorBridgeParams(
    outboundSpmWord = {bridge.outbound_word},
    outboundWords = {bridge.outbound_words},
    inboundSpmWord = {bridge.inbound_word},
    inboundWords = {bridge.inbound_words},
    outboundScale = CgraRequantParams(multiplier = 1, shift = 0),
    inboundScale = CgraRequantParams(multiplier = 1, shift = 0))
  val params = CGRASpmWindowParams(baseAddress, sizeBytes, Some(bridge), outboundScale = bridge.outboundScale)
  val windows: Map[String, CGRASpmWindowParams] = Map("cgra" -> params)
}}
"""
    return f"""package chipyard.socgen.generated

import chipyard.example.CGRASpmWindowParams
import chipyard.socgen.cgra.CgraRequantParams

// Generated by scripts/generate_cgra_spm_window.py. Do not edit.
object CGRASpmWindowGenerated {{
  val baseAddress: BigInt = BigInt("{contract.base_address:x}", 16)
  val sizeBytes: Int = {contract.size_bytes}
  val params = CGRASpmWindowParams(baseAddress, sizeBytes, outboundScale = CgraRequantParams(multiplier = 1, shift = 0))
  val windows: Map[String, CGRASpmWindowParams] = Map("cgra" -> params)
}}
"""


def header_text(contract: CgraSpmWindowContract, bridge: CgraBridge | None) -> str:
    bridge_fields = ""
    window_bytes = contract.size_bytes
    if bridge is not None:
        window_bytes = bridge.window_bytes
        bridge_fields = f"""#define CGRA_SPM_OUTBOUND_WORD {bridge.outbound_word}u
#define CGRA_SPM_INBOUND_WORD {bridge.inbound_word}u
#define CGRA_SPM_INBOUND_WORDS {bridge.inbound_words}u
"""
    return f"""/* Generated by scripts/generate_cgra_spm_window.py. Do not edit. */
#ifndef CGRA_SPM_WINDOW_H
#define CGRA_SPM_WINDOW_H

#include <stdint.h>

#define CGRA_SPM_WINDOW_BASE UINT64_C(0x{contract.base_address:x})
#define CGRA_SPM_WINDOW_SIZE_BYTES {window_bytes}u
{bridge_fields}
#endif
"""


def window_text(contract: CgraSpmWindowContract, bridge: CgraBridge | None) -> str:
    size = contract.size_bytes if bridge is None else bridge.window_bytes
    transform = ""
    if bridge is not None:
        transform = (
            ", Some(CgraTensorBridgeParams("
            f"outboundSpmWord = {bridge.outbound_word}, outboundWords = {bridge.outbound_words}, "
            f"inboundSpmWord = {bridge.inbound_word}, inboundWords = {bridge.inbound_words}, "
            "outboundScale = CgraRequantParams(multiplier = 1, shift = 0), "
            "inboundScale = CgraRequantParams(multiplier = 1, shift = 0)))"
        )
    return f'CGRASpmWindowParams(BigInt("{contract.base_address:x}", 16), {size}{transform}, outboundScale = CgraRequantParams(multiplier = 1, shift = 0))'


def instance_text(
    contracts: Mapping[str, CgraSpmWindowContract],
    bridges: Mapping[str, CgraBridge | None],
) -> str:
    name = next(iter(contracts))
    windows = ",\n".join(
        f'    "{name}" -> {window_text(contract, bridges[name])}'
        for name, contract in contracts.items()
    )
    imports = "\nimport chipyard.socgen.cgra.CgraRequantParams"
    if any(bridge is not None for bridge in bridges.values()):
        imports = (
            "\nimport chipyard.socgen.cgra.{CgraRequantParams, CgraTensorBridgeParams}"
        )
    return f"""package chipyard.socgen.generated

import chipyard.example.CGRASpmWindowParams{imports}

// Generated by scripts/generate_cgra_spm_window.py. Do not edit.
object CGRASpmWindowGenerated {{
  val windows: Map[String, CGRASpmWindowParams] = Map(
{windows})
  val params = windows("{name}")
  val baseAddress: BigInt = params.baseAddress
  val sizeBytes: Int = params.sizeBytes
}}
"""


def instance_header(
    contracts: Mapping[str, CgraSpmWindowContract],
    bridges: Mapping[str, CgraBridge | None],
) -> str:
    first = next(iter(contracts))
    text = header_text(contracts[first], bridges[first])
    fields = []
    for name, contract in contracts.items():
        prefix = name.upper()
        bridge = bridges[name]
        size = contract.size_bytes if bridge is None else bridge.window_bytes
        fields.extend(
            [
                f"#define {prefix}_SPM_WINDOW_BASE UINT64_C(0x{contract.base_address:x})",
                f"#define {prefix}_SPM_WINDOW_SIZE_BYTES {size}u",
            ]
        )
        if bridge is not None:
            fields.extend(
                [
                    f"#define {prefix}_SPM_OUTBOUND_WORD {bridge.outbound_word}u",
                    f"#define {prefix}_SPM_INBOUND_WORD {bridge.inbound_word}u",
                    f"#define {prefix}_SPM_INBOUND_WORDS {bridge.inbound_words}u",
                ]
            )
    return text.replace("\n#endif\n", "\n" + "\n".join(fields) + "\n\n#endif\n")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--soc-yaml", type=Path, default=DEFAULT_SOC)
    parser.add_argument("--cgra-scala", type=Path, default=DEFAULT_CGRA_SCALA)
    parser.add_argument(
        "--cache-block-scala", type=Path, default=DEFAULT_CACHE_BLOCK_SCALA
    )
    parser.add_argument("--scala-out", type=Path, default=DEFAULT_SCALA)
    parser.add_argument("--header-out", type=Path, default=DEFAULT_HEADER)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    metadata = load_metadata(args.cgra_scala.resolve())
    soc_path = args.soc_yaml.resolve()
    contract = load_contract(soc_path, metadata)
    config = load_config(
        soc_path, args.cgra_scala.resolve(), args.cache_block_scala.resolve()
    )
    document = yaml.safe_load(soc_path.read_text(encoding="utf-8"))
    if "instances" in document["communication"]:
        contracts = {
            name: CgraSpmWindowContract(accel.base, accel.size)
            for name, accel in config.instances.items()
            if accel.kind == "cgra"
        }
        write(args.scala_out, instance_text(contracts, config.bridges), args.check)
        write(args.header_out, instance_header(contracts, config.bridges), args.check)
        return 0
    write(args.scala_out, scala_text(contract, config.bridge), args.check)
    write(args.header_out, header_text(contract, config.bridge), args.check)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
