#!/usr/bin/env python3
"""Generate the CGRA SPM window address contract."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

import yaml

from generate_gemmini_ext_spm import (
    DEFAULT_SOC,
    is_power_of_two,
    require_int,
    require_mapping,
    write,
)

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CGRA_SCALA = (
    ROOT
    / "chipyard"
    / "generators"
    / "chipyard"
    / "src"
    / "main"
    / "scala"
    / "example"
    / "CGRAGenerated.scala"
)
DEFAULT_SCALA = (
    ROOT
    / "chipyard"
    / "generators"
    / "chipyard"
    / "src"
    / "main"
    / "scala"
    / "socgen"
    / "generated"
    / "CGRASpmWindowGenerated.scala"
)
DEFAULT_HEADER = ROOT / "tests" / "include" / "cgra_spm_window.h"


@dataclass(frozen=True)
class CgraSpmMetadata:
    data_width: int
    words: int

    @property
    def size_bytes(self) -> int:
        if self.data_width % 8 != 0:
            raise ValueError("generated CGRA SPM data width must contain whole bytes")
        return self.words * self.data_width // 8


@dataclass(frozen=True)
class CgraSpmWindowContract:
    base_address: int
    size_bytes: int


def load_metadata(path: Path) -> CgraSpmMetadata:
    text = path.read_text(encoding="utf-8")
    block = re.search(
        r"spmRead\s*=\s*CGRASpmReadParams\((?P<body>.*?)\n\s*\)", text, re.S
    )
    if block is None:
        raise ValueError(f"{path}: missing generated CGRA SPM metadata")
    body = block.group("body")
    enabled = re.search(r"enabled\s*=\s*(true|false)", body)
    data_width = re.search(r"dataWidth\s*=\s*(\d+)", body)
    words = re.search(r"words\s*=\s*(\d+)", body)
    if (
        enabled is None
        or enabled.group(1) != "true"
        or data_width is None
        or words is None
    ):
        raise ValueError(f"{path}: incomplete generated CGRA SPM metadata")
    return CgraSpmMetadata(int(data_width.group(1)), int(words.group(1)))


def load_contract(path: Path, metadata: CgraSpmMetadata) -> CgraSpmWindowContract:
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(document, Mapping):
        raise ValueError(f"{path}: expected a mapping")
    memory = require_mapping(document, "memory", path)
    window = require_mapping(memory, "cgra_spm_window", path)
    contract = CgraSpmWindowContract(
        base_address=require_int(window, "base_address", path),
        size_bytes=require_int(window, "size_bytes", path),
    )
    if not is_power_of_two(contract.size_bytes):
        raise ValueError(f"{path}: CGRA SPM window size must be a power of two")
    if contract.base_address % contract.size_bytes != 0:
        raise ValueError(f"{path}: CGRA SPM window base must be size aligned")
    if contract.size_bytes != metadata.size_bytes:
        raise ValueError(
            f"{path}: CGRA SPM window size {contract.size_bytes} does not match generated size {metadata.size_bytes}"
        )
    gemmini = require_mapping(memory, "gemmini_external_spm", path)
    gemmini_base = require_int(gemmini, "base_address", path)
    gemmini_size = require_int(gemmini, "size_bytes", path)
    if (
        contract.base_address < gemmini_base + gemmini_size
        and gemmini_base < contract.base_address + contract.size_bytes
    ):
        raise ValueError(f"{path}: CGRA and Gemmini SPM ranges overlap")
    return contract


def scala_text(contract: CgraSpmWindowContract) -> str:
    return f"""package chipyard.socgen.generated

import chipyard.example.CGRASpmWindowParams

// Generated by scripts/generate_cgra_spm_window.py. Do not edit.
object CGRASpmWindowGenerated {{
  val baseAddress: BigInt = BigInt("{contract.base_address:x}", 16)
  val sizeBytes: Int = {contract.size_bytes}
  val params = CGRASpmWindowParams(baseAddress)
}}
"""


def header_text(contract: CgraSpmWindowContract) -> str:
    return f"""/* Generated by scripts/generate_cgra_spm_window.py. Do not edit. */
#ifndef CGRA_SPM_WINDOW_H
#define CGRA_SPM_WINDOW_H

#include <stdint.h>

#define CGRA_SPM_WINDOW_BASE UINT64_C(0x{contract.base_address:x})
#define CGRA_SPM_WINDOW_SIZE_BYTES {contract.size_bytes}u

#endif
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--soc-yaml", type=Path, default=DEFAULT_SOC)
    parser.add_argument("--cgra-scala", type=Path, default=DEFAULT_CGRA_SCALA)
    parser.add_argument("--scala-out", type=Path, default=DEFAULT_SCALA)
    parser.add_argument("--header-out", type=Path, default=DEFAULT_HEADER)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    metadata = load_metadata(args.cgra_scala.resolve())
    contract = load_contract(args.soc_yaml.resolve(), metadata)
    write(args.scala_out, scala_text(contract), args.check)
    write(args.header_out, header_text(contract), args.check)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
