#!/usr/bin/env python3
"""Generate the shared-SPM hardware and C layout."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

import yaml

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOC = ROOT / "configs" / "soc" / "cgra_gemmini_soc.yaml"
DEFAULT_SCALA = (
    ROOT
    / "chipyard"
    / "generators"
    / "chipyard"
    / "src"
    / "main"
    / "scala"
    / "example"
    / "SharedSpmGenerated.scala"
)
DEFAULT_HEADER = ROOT / "tests" / "include" / "shared_spm.h"


@dataclass(frozen=True)
class SharedSpmContract:
    base_address: int
    size_bytes: int
    slot_count: int
    slot_size_bytes: int

    @property
    def slot_base(self) -> int:
        return (
            self.base_address + self.size_bytes - self.slot_count * self.slot_size_bytes
        )

    def slot_address(self, index: int) -> int:
        return self.slot_base + index * self.slot_size_bytes


def require_mapping(
    data: Mapping[str, object], key: str, source: Path
) -> Mapping[str, object]:
    value = data.get(key)
    if not isinstance(value, Mapping):
        raise ValueError(f"{source}: missing mapping '{key}'")
    return value


def require_int(data: Mapping[str, object], key: str, source: Path) -> int:
    value = data.get(key)
    if not isinstance(value, int) or isinstance(value, bool):
        raise ValueError(f"{source}: '{key}' must be an integer")
    return value


def is_power_of_two(value: int) -> bool:
    return value > 0 and value & (value - 1) == 0


def load_contract(path: Path) -> SharedSpmContract:
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(document, Mapping):
        raise ValueError(f"{path}: expected a mapping")
    memory = require_mapping(document, "memory", path)
    spm = require_mapping(memory, "shared_spm", path)
    slots = require_mapping(spm, "slots", path)
    contract = SharedSpmContract(
        base_address=require_int(spm, "base_address", path),
        size_bytes=require_int(spm, "size_bytes", path),
        slot_count=require_int(slots, "count", path),
        slot_size_bytes=require_int(slots, "size_bytes", path),
    )
    if not is_power_of_two(contract.size_bytes):
        raise ValueError(f"{path}: shared_spm.size_bytes must be a power of two")
    if contract.base_address % contract.size_bytes != 0:
        raise ValueError(f"{path}: shared_spm.base_address must be size aligned")
    if contract.slot_count <= 0 or contract.slot_size_bytes <= 0:
        raise ValueError(f"{path}: shared_spm slots must be non-empty")
    if contract.slot_count * contract.slot_size_bytes > contract.size_bytes:
        raise ValueError(f"{path}: shared_spm slots exceed the memory")
    return contract


def scala_text(contract: SharedSpmContract) -> str:
    addresses = ", ".join(
        f'BigInt("{contract.slot_address(index):x}", 16)'
        for index in range(contract.slot_count)
    )
    return f"""package chipyard.example

// Generated by scripts/generate_shared_spm.py. Do not edit.
object SharedSpmGenerated {{
  val baseAddress: BigInt = BigInt("{contract.base_address:x}", 16)
  val sizeBytes: Int = {contract.size_bytes}
  val slotCount: Int = {contract.slot_count}
  val slotSizeBytes: Int = {contract.slot_size_bytes}
  val slotBase: BigInt = BigInt("{contract.slot_base:x}", 16)
  val slotBases: Seq[BigInt] = Seq({addresses})
}}
"""


def header_text(contract: SharedSpmContract) -> str:
    lines = [
        "/* Generated by scripts/generate_shared_spm.py. Do not edit. */",
        "#ifndef SHARED_SPM_H",
        "#define SHARED_SPM_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define SHARED_SPM_BASE UINT64_C(0x{contract.base_address:x})",
        f"#define SHARED_SPM_SIZE_BYTES {contract.size_bytes}u",
        f"#define SHARED_SPM_SLOT_COUNT {contract.slot_count}u",
        f"#define SHARED_SPM_SLOT_SIZE_BYTES {contract.slot_size_bytes}u",
    ]
    for index in range(contract.slot_count):
        lines.append(
            f"#define SHARED_SPM_SLOT{index}_BASE UINT64_C(0x{contract.slot_address(index):x})"
        )
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def write(path: Path, content: str, check: bool) -> None:
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise ValueError(f"stale generated file: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--soc-yaml", type=Path, default=DEFAULT_SOC)
    parser.add_argument("--scala-out", type=Path, default=DEFAULT_SCALA)
    parser.add_argument("--header-out", type=Path, default=DEFAULT_HEADER)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    contract = load_contract(args.soc_yaml.resolve())
    write(args.scala_out, scala_text(contract), args.check)
    write(args.header_out, header_text(contract), args.check)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
