#!/usr/bin/env python3
"""Generate the CGRA SPM-control MMIO ABI."""

from __future__ import annotations

import argparse
from pathlib import Path

from generate_shared_spm import DEFAULT_SOC, load_contract, write

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SCALA = (
    ROOT
    / "chipyard"
    / "generators"
    / "chipyard"
    / "src"
    / "main"
    / "scala"
    / "example"
    / "CgraSpmControlGenerated.scala"
)
DEFAULT_HEADER = ROOT / "tests" / "include" / "cgra_spm_control_generated.h"
PAGE_SIZE_BYTES = 4096

REGISTERS = {
    "JOB_ID": 0x000,
    "SLOT": 0x008,
    "BYTES": 0x010,
    "MODE": 0x018,
    "SPM_WORD_ADDRESS": 0x020,
    "DMA_TAG": 0x028,
    "PACKET_COUNT": 0x030,
    "HEADER_SUBMIT": 0x038,
    "PACKET_LO": 0x040,
    "PACKET_MID": 0x048,
    "PACKET_HI": 0x050,
    "PACKET_TOP": 0x058,
    "PACKET_SUBMIT": 0x060,
    "JOB_SUBMIT": 0x068,
    "STEP_SUBMIT": 0x070,
    "RESULT_VALID": 0x080,
    "RESULT_POP": 0x088,
    "RESULT_JOB_ID": 0x090,
    "RESULT_SLOT": 0x098,
    "RESULT_BYTES": 0x0A0,
    "RESULT_STAGE": 0x0A8,
    "RESULT_STATUS": 0x0B0,
    "RESULT_DETAIL": 0x0B8,
    "RESULT_DATA": 0x0C0,
}

MODES = {"AUTO": 0, "MANUAL": 1}
STAGES = {"PRODUCER": 0, "TRANSFER": 1, "CONSUMER": 2}
STATUSES = {
    "SUCCESS": 0,
    "INVALID_JOB": 1,
    "INVALID_SLOT": 2,
    "INVALID_LENGTH": 3,
    "IDENTITY_MISMATCH": 4,
    "STAGE_FAILURE": 5,
}


def scala_text(base_address: int) -> str:
    values = "\n".join(
        f"  val {name}: Int = 0x{offset:03x}" for name, offset in REGISTERS.items()
    )
    return f"""package chipyard.example

// Generated by scripts/generate_cgra_spm_control.py. Do not edit.
object CgraSpmControlGenerated {{
  val baseAddress: BigInt = BigInt("{base_address:x}", 16)
  val pageSizeBytes: Int = {PAGE_SIZE_BYTES}
{values}
}}
"""


def header_text(base_address: int) -> str:
    lines = [
        "/* Generated by scripts/generate_cgra_spm_control.py. Do not edit. */",
        "#ifndef CGRA_SPM_CONTROL_GENERATED_H",
        "#define CGRA_SPM_CONTROL_GENERATED_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define CGRA_SPM_CONTROL_BASE UINT64_C(0x{base_address:x})",
        f"#define CGRA_SPM_CONTROL_PAGE_SIZE_BYTES {PAGE_SIZE_BYTES}u",
        "",
    ]
    lines.extend(
        f"#define CGRA_SPM_CONTROL_{name} 0x{offset:03x}u"
        for name, offset in REGISTERS.items()
    )
    lines.append("")
    lines.extend(
        f"#define CGRA_SPM_MODE_{name} {value}u" for name, value in MODES.items()
    )
    lines.extend(
        f"#define CGRA_SPM_STAGE_{name} {value}u" for name, value in STAGES.items()
    )
    lines.extend(
        f"#define CGRA_SPM_STATUS_{name} {value}u" for name, value in STATUSES.items()
    )
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--soc-yaml", type=Path, default=DEFAULT_SOC)
    parser.add_argument("--scala-out", type=Path, default=DEFAULT_SCALA)
    parser.add_argument("--header-out", type=Path, default=DEFAULT_HEADER)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    contract = load_contract(args.soc_yaml.resolve())
    base_address = contract.base_address + contract.size_bytes
    write(args.scala_out, scala_text(base_address), args.check)
    write(args.header_out, header_text(base_address), args.check)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
