#!/usr/bin/env python3
"""Generate accelerator instance identities and CPU-visible addresses."""

from __future__ import annotations

import argparse
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Mapping

import yaml

from generate_gemmini_ext_spm import DEFAULT_SOC, DEFAULT_SCALA, write

SCALA_OUT = DEFAULT_SCALA.with_name("AccelGenerated.scala")
HEADER_OUT = Path(__file__).resolve().parents[1] / "tests/include/accel_generated.h"
PAGE_BYTES = 4096
SPM_KEYS = {"gemmini": "gemmini_external_spm", "cgra": "cgra_spm_window"}
CONTROL_PAGES = {"cgra": 0, "gemmini": 1, "aes": 2}


@dataclass(frozen=True)
class Accel:
    name: str
    kind: str
    id: int
    base: int
    size: int
    control: int = 0


@dataclass(frozen=True)
class AccelLayout:
    enabled: bool
    instances: tuple[Accel, ...]
    control_base: int
    auto_link_address: int
    page_count: int


def instance_layout(document: Mapping[str, object]) -> AccelLayout:
    communication = document["communication"]
    memory = document["memory"]
    enabled = "instances" in communication
    names = dict.fromkeys(stage["endpoint"] for stage in communication["stages"])
    values = communication.get("instances", {name: {"type": name} for name in names})
    counts = dict.fromkeys(SPM_KEYS, 0)
    instances = []
    for index, (name, value) in enumerate(values.items()):
        kind = value["type"]
        if enabled and kind not in {"gemmini", "cgra", "pool"}:
            raise ValueError(f"instance '{name}' has unsupported type '{kind}'")
        base, size = 0, 0
        if kind in SPM_KEYS:
            spm = memory[SPM_KEYS[kind]]
            size = spm["size_bytes"]
            base = value.get("base_address", spm["base_address"] + counts[kind] * size)
            counts[kind] += 1
        instances.append(Accel(name, kind, index, base, size))
    ranges = (
        [(accel.base, accel.size) for accel in instances if accel.size]
        if enabled
        else [
            (memory[key]["base_address"], memory[key]["size_bytes"])
            for key in SPM_KEYS.values()
        ]
    )
    end = max(base + size for base, size in ranges)
    control_base = (end + PAGE_BYTES - 1) // PAGE_BYTES * PAGE_BYTES
    for index, accel in enumerate(instances):
        page = accel.id if enabled else CONTROL_PAGES.get(accel.kind)
        control = 0 if page is None else control_base + page * PAGE_BYTES
        instances[index] = replace(accel, control=control)
    root_page = len(instances) if enabled else 3
    return AccelLayout(
        enabled,
        tuple(instances),
        control_base,
        control_base + root_page * PAGE_BYTES,
        root_page + 1,
    )


def load_layout(path: Path) -> AccelLayout:
    return instance_layout(yaml.safe_load(path.read_text(encoding="utf-8")))


def scala_text(layout: AccelLayout) -> str:
    instances = ",\n".join(
        f'    AccelSpec("{accel.name}", "{accel.kind}", {accel.id}, BigInt("{accel.base:x}", 16), {accel.size}, BigInt("{accel.control:x}", 16))'
        for accel in layout.instances
    )
    return f"""package chipyard.socgen.generated

import chipyard.socgen.link.AccelSpec

// Generated by scripts/generate_accels.py. Do not edit.
object AccelGenerated {{
  val enabled: Boolean = {str(layout.enabled).lower()}
  val controlBase: BigInt = BigInt("{layout.control_base:x}", 16)
  val autoLinkAddress: BigInt = BigInt("{layout.auto_link_address:x}", 16)
  val pageSizeBytes: Int = {PAGE_BYTES}
  val instances: Seq[AccelSpec] = Seq(
{instances})
}}
"""


def header_text(layout: AccelLayout) -> str:
    instances = "\n".join(
        f"static const accel_t {accel.name.upper()} = {{.id = {accel.id}u, .control = UINT64_C(0x{accel.control:x}), .spm = UINT64_C(0x{accel.base:x}), .spm_bytes = {accel.size}u}};"
        for accel in layout.instances
    )
    return f"""/* Generated by scripts/generate_accels.py. Do not edit. */
#ifndef ACCEL_GENERATED_H
#define ACCEL_GENERATED_H

#include "accel.h"

#define ACCEL_ROUTED {int(layout.enabled)}
#define ACCEL_COUNT {len(layout.instances)}u

{instances}

#endif
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--soc-yaml", type=Path, default=DEFAULT_SOC)
    parser.add_argument("--scala-out", type=Path, default=SCALA_OUT)
    parser.add_argument("--header-out", type=Path, default=HEADER_OUT)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    layout = load_layout(args.soc_yaml)
    write(args.scala_out, scala_text(layout), args.check)
    write(args.header_out, header_text(layout), args.check)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
