#!/usr/bin/env python3
"""Generate the elaborated AutoLink topology."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Mapping

import yaml

from generate_gemmini_ext_spm import DEFAULT_SOC, write

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SCALA = (
    ROOT
    / "chipyard"
    / "generators"
    / "chipyard"
    / "src"
    / "main"
    / "scala"
    / "socgen"
    / "generated"
    / "AutoLinksGenerated.scala"
)


def load_links(path: Path) -> list[tuple[str, str]]:
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(document, Mapping):
        raise ValueError(f"{path}: expected a mapping")
    communication = document.get("communication")
    if not isinstance(communication, Mapping):
        raise ValueError(f"{path}: missing mapping 'communication'")
    auto_links = communication.get("auto_links")
    if not isinstance(auto_links, list) or not auto_links:
        raise ValueError(f"{path}: 'auto_links' must be a non-empty list")

    links = []
    for index, value in enumerate(auto_links):
        if not isinstance(value, Mapping):
            raise ValueError(f"{path}: auto_links[{index}] must be a mapping")
        source = value.get("source")
        destination = value.get("destination")
        if not isinstance(source, str) or not isinstance(destination, str):
            raise ValueError(
                f"{path}: auto_links[{index}] needs source and destination"
            )
        links.append((source, destination))
    if len(set(links)) != len(links):
        raise ValueError(f"{path}: duplicate auto link")
    return links


def scala_text(links: list[tuple[str, str]]) -> str:
    values = ",\n".join(
        f'    AutoLinkSpec(source = "{source}", destination = "{destination}")'
        for source, destination in links
    )
    return f"""package chipyard.socgen.generated

import chipyard.socgen.link.AutoLinkSpec

// Generated by scripts/generate_auto_links.py. Do not edit.
object AutoLinksGenerated {{
  val links: Seq[AutoLinkSpec] = Seq(
{values})
}}
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--soc-yaml", type=Path, default=DEFAULT_SOC)
    parser.add_argument("--scala-out", type=Path, default=DEFAULT_SCALA)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    links = load_links(args.soc_yaml.resolve())
    write(args.scala_out, scala_text(links), args.check)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
