#!/usr/bin/env python3
"""Generate the Gemmini external-SPM parameters."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

import yaml

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOC = ROOT / "configs" / "soc" / "cgra_gemmini_soc.yaml"
DEFAULT_SCALA = (
    ROOT
    / "chipyard"
    / "generators"
    / "chipyard"
    / "src"
    / "main"
    / "scala"
    / "socgen"
    / "generated"
    / "GemminiExternalSpmGenerated.scala"
)
DEFAULT_HEADER = ROOT / "tests" / "include" / "gemmini_ext_spm.h"


@dataclass(frozen=True)
class GemminiExternalSpmContract:
    base_address: int
    size_bytes: int


def require_mapping(
    data: Mapping[str, object], key: str, source: Path
) -> Mapping[str, object]:
    value = data.get(key)
    if not isinstance(value, Mapping):
        raise ValueError(f"{source}: missing mapping '{key}'")
    return value


def require_int(data: Mapping[str, object], key: str, source: Path) -> int:
    value = data.get(key)
    if not isinstance(value, int) or isinstance(value, bool):
        raise ValueError(f"{source}: '{key}' must be an integer")
    return value


def is_power_of_two(value: int) -> bool:
    return value > 0 and value & (value - 1) == 0


def load_contract(path: Path) -> GemminiExternalSpmContract:
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(document, Mapping):
        raise ValueError(f"{path}: expected a mapping")
    memory = require_mapping(document, "memory", path)
    spm = require_mapping(memory, "gemmini_external_spm", path)
    contract = GemminiExternalSpmContract(
        base_address=require_int(spm, "base_address", path),
        size_bytes=require_int(spm, "size_bytes", path),
    )
    if not is_power_of_two(contract.size_bytes):
        raise ValueError(f"{path}: external SPM size must be a power of two")
    if contract.base_address % contract.size_bytes != 0:
        raise ValueError(f"{path}: external SPM base must be size aligned")
    return contract


def scala_text(contract: GemminiExternalSpmContract) -> str:
    return f"""package chipyard.socgen.generated

import chipyard.socgen.gemmini.GemminiExternalSpmParams

// Generated by scripts/generate_gemmini_ext_spm.py. Do not edit.
object GemminiExternalSpmGenerated {{
  val baseAddress: BigInt = BigInt("{contract.base_address:x}", 16)
  val sizeBytes: Int = {contract.size_bytes}
  val params = GemminiExternalSpmParams(baseAddress, sizeBytes)
}}
"""


def header_text(contract: GemminiExternalSpmContract) -> str:
    return f"""/* Generated by scripts/generate_gemmini_ext_spm.py. Do not edit. */
#ifndef GEMMINI_EXT_SPM_H
#define GEMMINI_EXT_SPM_H

#include <stdint.h>

#define GEMMINI_EXT_SPM_BASE UINT64_C(0x{contract.base_address:x})
#define GEMMINI_EXT_SPM_SIZE_BYTES {contract.size_bytes}u

#endif
"""


def write(path: Path, content: str, check: bool) -> None:
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise ValueError(f"stale generated file: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--soc-yaml", type=Path, default=DEFAULT_SOC)
    parser.add_argument("--scala-out", type=Path, default=DEFAULT_SCALA)
    parser.add_argument("--header-out", type=Path, default=DEFAULT_HEADER)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    contract = load_contract(args.soc_yaml.resolve())
    write(args.scala_out, scala_text(contract), args.check)
    write(args.header_out, header_text(contract), args.check)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
