#!/usr/bin/env python3
"""Generate the CGRA AutoLink-control MMIO ABI."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Mapping

import yaml

from generate_gemmini_ext_spm import (
    DEFAULT_SOC,
    require_int,
    require_mapping,
    write,
)

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SCALA = (
    ROOT
    / "chipyard"
    / "generators"
    / "chipyard"
    / "src"
    / "main"
    / "scala"
    / "socgen"
    / "generated"
    / "CgraLinkControlGenerated.scala"
)
DEFAULT_HEADER = ROOT / "tests" / "include" / "cgra_link_control_generated.h"
PAGE_SIZE_BYTES = 4096

REGISTERS = {
    "PACKET_COUNT": 0x000,
    "CONFIG_SUBMIT": 0x008,
    "RESULT_VALID": 0x010,
    "RESULT_POP": 0x018,
    "RESULT_STATUS": 0x020,
    "RESULT_DETAIL": 0x028,
    "RESULT_DATA": 0x030,
}

STATUSES = {
    "SUCCESS": 0,
    "SOURCE_FAILURE": 1,
    "SINK_FAILURE": 2,
}

SPM_NAMES = ("gemmini_external_spm", "cgra_spm_window")


def align_up(value: int, alignment: int) -> int:
    return (value + alignment - 1) // alignment * alignment


def load_spm_ranges(path: Path) -> list[tuple[int, int]]:
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(document, Mapping):
        raise ValueError(f"{path}: expected a mapping")
    memory = require_mapping(document, "memory", path)
    ranges = []
    for name in SPM_NAMES:
        spm = require_mapping(memory, name, path)
        base = require_int(spm, "base_address", path)
        size = require_int(spm, "size_bytes", path)
        if size <= 0:
            raise ValueError(f"{path}: '{name}.size_bytes' must be positive")
        ranges.append((base, size))
    return ranges


def control_address(path: Path) -> int:
    end = max(base + size for base, size in load_spm_ranges(path))
    return align_up(end, PAGE_SIZE_BYTES)


def scala_text(base_address: int) -> str:
    values = "\n".join(
        f"  val {name}: Int = 0x{offset:03x}" for name, offset in REGISTERS.items()
    )
    return f"""package chipyard.socgen.generated

// Generated by scripts/generate_cgra_link_control.py. Do not edit.
object CgraLinkControlGenerated {{
  val baseAddress: BigInt = BigInt("{base_address:x}", 16)
  val pageSizeBytes: Int = {PAGE_SIZE_BYTES}
{values}
}}
"""


def header_text(base_address: int) -> str:
    lines = [
        "/* Generated by scripts/generate_cgra_link_control.py. Do not edit. */",
        "#ifndef CGRA_LINK_CONTROL_GENERATED_H",
        "#define CGRA_LINK_CONTROL_GENERATED_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define CGRA_LINK_CONTROL_BASE UINT64_C(0x{base_address:x})",
        f"#define CGRA_LINK_CONTROL_PAGE_SIZE_BYTES {PAGE_SIZE_BYTES}u",
        "",
    ]
    lines.extend(
        f"#define CGRA_LINK_CONTROL_{name} 0x{offset:03x}u"
        for name, offset in REGISTERS.items()
    )
    lines.append("")
    lines.extend(
        f"#define AUTO_LINK_STATUS_{name} {value}u" for name, value in STATUSES.items()
    )
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--soc-yaml", type=Path, default=DEFAULT_SOC)
    parser.add_argument("--scala-out", type=Path, default=DEFAULT_SCALA)
    parser.add_argument("--header-out", type=Path, default=DEFAULT_HEADER)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    base_address = control_address(args.soc_yaml.resolve())
    write(args.scala_out, scala_text(base_address), args.check)
    write(args.header_out, header_text(base_address), args.check)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
