#!/usr/bin/env python3
"""Generate Chipyard-side Scala metadata for OpenFPGA demos."""

from __future__ import annotations

from openfpga_bitstream import PackedBitstream
from openfpga_demo_config import ROOT, DemoConfig, FieldSpec


CHIPYARD_CONFIG_GENERATED = (
    ROOT
    / "chipyard"
    / "generators"
    / "chipyard"
    / "src"
    / "main"
    / "scala"
    / "config"
    / "OpenFPGAConfigGenerated.scala"
)


def _scala_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _field_seq(fields: list[FieldSpec]) -> str:
    if not fields:
        return "Seq.empty"
    rendered = ", ".join(
        f"OpenFPGAUserField({_scala_string(field.name)}, {field.width}, {field.lsb})"
        for field in fields
    )
    return f"Seq({rendered})"


def _compatible(peripheral_name: str) -> str:
    return "ucbbar," + peripheral_name.replace("_", "-").lower()


def write_scala_generated(demo: DemoConfig, bitstream: PackedBitstream) -> None:
    cfg = demo.architecture.config_protocol
    text = f"""package chipyard.example

// Auto-generated by scripts/openfpga_chipyard_codegen.py.
case class OpenFPGAUserField(name: String, width: Int, lsb: Int)

object {demo.chipyard.scala_object} {{
  val Name = {_scala_string(demo.name)}
  val ApplicationName = {_scala_string(demo.application.name)}
  val ConfigName = {_scala_string(demo.chipyard.config_name)}
  val PeripheralName = {_scala_string(demo.chipyard.peripheral_name)}
  val Compatible = {_scala_string(_compatible(demo.chipyard.peripheral_name))}
  val WrapperModule = {_scala_string(demo.chipyard.wrapper_module)}
  val WrapperPath = {_scala_string(str(demo.wrapper_path.resolve()))}

  val BaseAddress = BigInt("{demo.soc.base_address:x}", 16)
  val Size = BigInt("{demo.soc.size:x}", 16)

  val BitstreamLength = {bitstream.parsed_length}
  val CfgWordWidth = {cfg.word_width}
  val CfgAddrWidth = {cfg.address_width}
  val CfgDataWidth = {cfg.data_width}

  val InputRegisterName = {_scala_string(demo.user_interface.input_register.name)}
  val InputWidth = {demo.input_width}
  val InputFields = {_field_seq(demo.user_interface.input_register.fields)}

  val OutputRegisterName = {_scala_string(demo.user_interface.output_register.name)}
  val OutputWidth = {demo.output_width}
  val OutputFields = {_field_seq(demo.user_interface.output_register.fields)}
}}
"""
    demo.scala_generated_path.parent.mkdir(parents=True, exist_ok=True)
    demo.scala_generated_path.write_text(text, encoding="utf-8")


def write_chipyard_config(demo: DemoConfig) -> None:
    text = f"""package chipyard

import org.chipsalliance.cde.config.Config

// Auto-generated by scripts/openfpga_chipyard_codegen.py.
class {demo.chipyard.config_name} extends Config(
  new chipyard.example.WithOpenFPGADemo() ++
  new freechips.rocketchip.rocket.WithNHugeCores(1) ++
  new chipyard.config.AbstractConfig)
"""
    CHIPYARD_CONFIG_GENERATED.parent.mkdir(parents=True, exist_ok=True)
    CHIPYARD_CONFIG_GENERATED.write_text(text, encoding="utf-8")
