array_config:
  columns: 4
  rows: 4
  compiled_ii: 6
  cores:
    - column: 0
      row: 0
      core_id: "0"
      entries:
        - entry_id: "entry0"
          instructions:
            - index_per_ii: 0
              operations:
                - opcode: "GRANT_ONCE"
                  id: 1
                  time_step: 0
                  invalid_iterations: 0
                  src_operands:
                    - operand: "#0"
                      color: "RED"
                  dst_operands:
                    - operand: "$0"
                      color: "RED"
            - index_per_ii: 1
              operations:
                - opcode: "PHI_START"
                  id: 2
                  time_step: 1
                  invalid_iterations: 0
                  src_operands:
                    - operand: "$0"
                      color: "RED"
                    - operand: "$8"
                      color: "RED"
                  dst_operands:
                    - operand: "$0"
                      color: "RED"
            - index_per_ii: 2
              operations:
                - opcode: "ADD"
                  id: 3
                  time_step: 2
                  invalid_iterations: 0
                  src_operands:
                    - operand: "$0"
                      color: "RED"
                    - operand: "#1"
                      color: "RED"
                  dst_operands:
                    - operand: "$8"
                      color: "RED"
            - index_per_ii: 3
              operations:
                - opcode: "ICMP_EQ"
                  id: 4
                  time_step: 3
                  invalid_iterations: 0
                  src_operands:
                    - operand: "$8"
                      color: "RED"
                    - operand: "#32"
                      color: "RED"
                  dst_operands:
                    - operand: "$16"
                      color: "RED"
            - index_per_ii: 4
              operations:
                - opcode: "GRANT_PREDICATE"
                  id: 5
                  time_step: 4
                  invalid_iterations: 0
                  src_operands:
                    - operand: "$8"
                      color: "RED"
                    - operand: "$16"
                      color: "RED"
                  dst_operands:
                    - operand: "$24"
                      color: "RED"
            - index_per_ii: 5
              operations:
                - opcode: "RETURN_VALUE"
                  id: 6
                  time_step: 5
                  invalid_iterations: 0
                  src_operands:
                    - operand: "$24"
                      color: "RED"
