array_config:
  columns: 4
  rows: 4
  compiled_ii: 3
  cores:
    - column: 3
      row: 0
      core_id: "3"
      entries:
        - entry_id: "entry0"
          instructions:
            - index_per_ii: 0
              operations:
                - opcode: "GRANT_ONCE"
                  id: 1
                  time_step: 0
                  invalid_iterations: 0
                  src_operands:
                    - operand: "#128"
                      color: "RED"
                  dst_operands:
                    - operand: "$0"
                      color: "RED"
            - index_per_ii: 1
              operations:
                - opcode: "LOAD"
                  id: 2
                  time_step: 1
                  invalid_iterations: 0
                  src_operands:
                    - operand: "$0"
                      color: "RED"
                  dst_operands:
                    - operand: "$0"
                      color: "RED"
            - index_per_ii: 2
              operations:
                - opcode: "RETURN_VALUE"
                  id: 3
                  time_step: 2
                  invalid_iterations: 0
                  src_operands:
                    - operand: "$0"
                      color: "RED"
