array_config:
  columns: 4
  rows: 4
  compiled_ii: 3
  cores:
    - column: 0
      row: 0
      core_id: "0"
      entries:
        - entry_id: "entry0"
          instructions:
            - index_per_ii: 0
              operations:
                - opcode: "GRANT_ONCE"
                  id: 1
                  time_step: 0
                  invalid_iterations: 0
                  src_operands:
                    - operand: "#123"
                      color: "RED"
                  dst_operands:
                    - operand: "EAST"
                      color: "RED"
    - column: 1
      row: 0
      core_id: "1"
      entries:
        - entry_id: "entry0"
          instructions:
            - index_per_ii: 0
              operations:
                - opcode: "DATA_MOV"
                  id: 2
                  time_step: 0
                  invalid_iterations: 0
                  src_operands:
                    - operand: "WEST"
                      color: "RED"
                  dst_operands:
                    - operand: "$0"
                      color: "RED"
            - index_per_ii: 1
              operations:
                - opcode: "RETURN_VALUE"
                  id: 3
                  time_step: 1
                  invalid_iterations: 0
                  src_operands:
                    - operand: "$0"
                      color: "RED"
